name: slug
version: 1.0.0
description: Terminal Spinners  
repository: 

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0
  path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
