name: slug
version: 1.0.0-dev-1
description: Terminal Spinners  
repository: https://github.com/shan-shaji/slug.git

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ansi_escapes: ^1.0.0-dev.3
  chalk: ^1.2.0
  meta: ^1.3.0
  path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
