name: slug_example
version: 1.0.0
description: A library to help in building Dart command-line apps.
repository: 

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0
  path: ^1.8.0

  slug:
    path: ../

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
